// ...existing code...
<Menu>
  // ...existing code...
  <MenuItem component={Link} to="/me">
    <ListItemIcon>
      <Person fontSize="small" />
    </ListItemIcon>
    My Profile
  </MenuItem>
  // ...existing code...
</Menu>;
// ...existing code...
